FROM node:25

RUN apt-get update

RUN apt-get install -y python3 python-is-python3

# Create app directory
WORKDIR /usr/src/app

COPY . .

RUN npm install
RUN npm run build-themes:dev
RUN npm run build:ssr

EXPOSE 4000

CMD [ "node", "dist/frontend/server/server.js" ]